services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations screener &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8042"
    volumes:
      - .:/app
    ports:
      - "8042:8042"
    env_file:
      - .env