services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations screener && \
                    python manage.py migrate && \
                    python manage.py fetch_markets && \
                    python manage.py update_value_area && \
                    python manage.py crontab add && \
                    python manage.py runserver 0.0.0.0:8042"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8042:8042"
    env_file:
      - .env